name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build Rust
        run: |
          cd src/wasm-crypto
          cargo build --verbose          
          wasm-pack build
          
      - name: Commit Rust build and Push Changes
        run: |
          git config --local user.email "pritam.prasd@gmail.com"
          git config --local user.name "update-rust-build-files-script"
          git add .
          git diff --quiet || git commit -m "Automated update for rust bulid files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

