name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Commit Rust build and Push Changes
        run: |
          cd src/wasm-crypto
          git config --local user.email "mail@pritam.dev"
          git config --local user.name "update-rust-build-files-script"
          git pull
          wasm-pack build
          git add .
          git diff --quiet || git commit -m "Automated update for rust bulid files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

